[package]
name = "tapstack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etherparse = "0.19.0"
nix = { version = "0.27.1", features = ["fs", "net", "ioctl", "poll"] }
rand = "0.9.2"
